'use client';
import { Profile } from '@/lib/profile';
import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';
export function download(data:string,name:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
export function vcard(p:Profile){const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');download(['BEGIN:VCARD','VERSION:3.0',`FN:${escape(p.name)}`,`TITLE:${escape(p.career)}`,`EMAIL:${escape(p.email)}`,`TEL:${escape(p.phone)}`,'END:VCARD'].join('\r\n'),`${p.name}.vcf`,'text/vcard');}
export function cv(p:Profile){const doc=new jsPDF();const colors:Record<string,[number,number,number]>={Profesional:[34,43,68],Minimalista:[45,45,45],Creativa:[114,71,204],Tecnológica:[15,111,124]};const color=colors[p.template]||colors.Profesional;let y=22;function line(t:string,size=10,bold=false){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);const lines=doc.splitTextToSize(t,170);for(const l of lines){if(y>276){doc.addPage();y=22;}doc.text(l,20,y);y+=size*.45+2;}y+=2;}if(p.template==='Profesional'){doc.setFillColor(...color);doc.rect(0,0,210,52,'F');doc.setTextColor(255,255,255);}else if(p.template==='Creativa'){doc.setFillColor(...color);doc.rect(0,0,7,297,'F');doc.setTextColor(...color);}else if(p.template==='Tecnológica'){doc.setFillColor(237,246,246);doc.rect(0,0,210,54,'F');doc.setDrawColor(...color);doc.line(20,49,190,49);doc.setFont('courier');doc.setTextColor(...color);}else{doc.setTextColor(...color);}line(p.name,25,true);line(p.career,12);y=Math.max(y,62);doc.setTextColor(70,70,80);line([p.email,p.phone,p.location].filter(Boolean).join(' | '),9);line(p.about||p.bio);for(const [label,entries] of [['Formación académica',p.education],['Experiencia',p.experience],['Reconocimientos',p.awards]] as const){if(!entries.length)continue;y+=4;doc.setTextColor(...color);line(label,14,true);doc.setTextColor(70,70,80);for(const e of entries){line(e.title,11,true);line(`${e.organization} · ${e.period}`,9);line(e.description);}}if(p.skills.length){line('Habilidades',14,true);line(p.skills.map(s=>s.name).join(' · '));}if(p.projects.length){line('Proyectos',14,true);for(const pr of p.projects){line(pr.title,11,true);line(pr.description);line(`${pr.role} | ${pr.technologies}`,9);if(pr.url||pr.repository)line(pr.url||pr.repository,9);}}doc.save(`CV-${p.name}-${p.template}.pdf`);}
export async function cardDownload(p:Profile,slug:string,vertical:boolean,pdf:boolean){const canvas=document.createElement('canvas');canvas.width=vertical?760:1200;canvas.height=vertical?1100:680;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#f5f3fc';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#202136';ctx.fillRect(0,0,canvas.width,120);ctx.fillStyle='#fff';ctx.font='bold 36px Arial';ctx.fillText('EProfile',50,75);let x=50,y=200;if(p.photo){try{const img=await loadImage(p.photo);ctx.save();ctx.beginPath();ctx.arc(100,200,50,0,Math.PI*2);ctx.clip();ctx.drawImage(img,50,150,100,100);ctx.restore();y=300;}catch{}}ctx.fillStyle='#24243c';ctx.font='bold 38px Arial';ctx.fillText(p.name,x,y);ctx.font='22px Arial';const words=p.career.split(' ');let line='';y+=45;for(const word of words){if(ctx.measureText(line+word).width>canvas.width-100){ctx.fillText(line,x,y);line='';y+=30;}line+=word+' ';}ctx.fillText(line,x,y);y+=65;ctx.font='22px Arial';ctx.fillText(p.email,x,y);ctx.fillText(p.phone,x,y+38);const url=`${location.origin}/${slug}`;const qr=await loadImage(await QRCode.toDataURL(url,{width:230,margin:1}));ctx.drawImage(qr,vertical?50:900,vertical?650:300,220,220);ctx.font='20px Arial';ctx.fillText(url.replace(/^https?:\/\//,''),50,canvas.height-65);const data=canvas.toDataURL('image/png');if(pdf){const doc=new jsPDF({orientation:vertical?'portrait':'landscape',unit:'px',format:[canvas.width,canvas.height]});doc.addImage(data,'PNG',0,0,canvas.width,canvas.height);doc.save(`tarjeta-${slug}.pdf`);}else{const a=document.createElement('a');a.href=data;a.download=`tarjeta-${slug}.png`;a.click();}}
function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>resolve(im);im.onerror=reject;im.src=src;});}

