export type Entry = { id:string; title:string; organization:string; period:string; description:string };
export type Project = { id:string; title:string; description:string; technologies:string; role:string; academic:boolean; url:string; repository:string; color:string };
export type Profile = { name:string; career:string; bio:string; about:string; availability:string; location:string; photo:string; email:string; phone:string; linkedin:string; github:string; education:Entry[]; experience:Entry[]; skills:{id:string;name:string;category:string}[]; projects:Project[]; awards:Entry[]; template:string };
export const demoProfile:Profile = {
 name:'Mauricio Vázquez', career:'Ingeniería en Sistemas y Negocios Digitales', bio:'Transformo ideas en soluciones digitales. Me apasiona el desarrollo web, la tecnología y crear experiencias que generen un impacto real.', about:'Soy estudiante de Ingeniería en Sistemas y Negocios Digitales, con interés en el desarrollo de software y la innovación. Disfruto conectar la tecnología con los negocios para resolver problemas reales. Actualmente busco una oportunidad para aprender, colaborar y aportar mis ideas en un equipo de desarrollo.', availability:'Disponible para prácticas', location:'Monterrey, Nuevo León', photo:'/images/mauricio.jpg', email:'mauricio.vazquez@example.com', phone:'+52 81 1234 5678', linkedin:'https://www.linkedin.com/', github:'https://github.com/',
 education:[{id:'e1',title:'Ingeniería en Sistemas y Negocios Digitales',organization:'Universidad Autónoma de Nuevo León',period:'2022 — Actualidad',description:'8.º semestre · Enfoque en desarrollo de software y transformación digital.'}],
 experience:[{id:'x1',title:'Desarrollador web · Servicio social',organization:'Laboratorio de Innovación UANL',period:'Ene 2025 — Jun 2025',description:'Desarrollo de una plataforma de gestión de proyectos para estudiantes. Colaboración con un equipo de 4 personas utilizando metodologías ágiles.'}],
 skills:[{id:'s1',name:'React',category:'Técnicas'},{id:'s2',name:'Next.js',category:'Técnicas'},{id:'s3',name:'JavaScript',category:'Técnicas'},{id:'s4',name:'MongoDB',category:'Técnicas'},{id:'s5',name:'Figma',category:'Técnicas'},{id:'s6',name:'Trabajo en equipo',category:'Blandas'},{id:'s7',name:'Resolución de problemas',category:'Blandas'}],
 projects:[{id:'p1',title:'Campus Connect',description:'Una plataforma que conecta estudiantes, eventos y oportunidades dentro de la universidad.',technologies:'React, Node.js, MongoDB',role:'Desarrollador full stack',academic:true,url:'',repository:'https://github.com/',color:'violet'},{id:'p2',title:'Fintrack',description:'Dashboard de finanzas personales para tomar mejores decisiones y alcanzar tus metas.',technologies:'Next.js, TypeScript, Tailwind',role:'Diseño UX/UI y desarrollo',academic:true,url:'',repository:'https://github.com/',color:'mint'},{id:'p3',title:'EcoMarket',description:'Un marketplace de productos sustentables que impulsa a los pequeños negocios locales.',technologies:'React, Express, MongoDB',role:'Desarrollador frontend',academic:true,url:'',repository:'https://github.com/',color:'peach'}],
 awards:[{id:'a1',title:'Desarrollo web con React',organization:'Meta · Coursera',period:'2025',description:'Certificación profesional en desarrollo frontend.'}],template:'Profesional'
};
export function completion(p:Profile) { const items=[p.name,p.career,p.bio,p.photo,p.about,p.email,p.phone,p.linkedin,p.github,p.education.length,p.experience.length,p.skills.length,p.projects.length,p.awards.length]; return Math.round(items.filter(Boolean).length/items.length*100); }
export function profileStatus(p:Profile,published?:Profile|null){return published?'Publicado':p.name||p.career?'Borrador':'Vacío';}
export const emptyProfile:Profile={name:'',career:'',bio:'',about:'',availability:'Disponible para prácticas',location:'',photo:'',email:'',phone:'',linkedin:'',github:'',education:[],experience:[],skills:[],projects:[],awards:[],template:'Profesional'};


