import { NextResponse } from 'next/server';
import { session, sameOrigin } from '@/lib/auth';
import { db } from '@/lib/db';
import { ObjectId } from 'mongodb';
import { hash } from 'bcryptjs';
import { emptyProfile } from '@/lib/profile';
import { profileSchema } from '@/lib/validation';
export async function GET(){const user=await session();if(user?.role!=='admin')return new Response(null,{status:403});const database=await db();return NextResponse.json({users:await database.collection('users').find({role:'student'},{projection:{password:0}}).toArray(),settings:await database.collection('settings').findOne({key:'general'}),requests:await database.collection('recoveryRequests').find({resolved:false}).toArray()});}
export async function POST(req:Request){if(!sameOrigin(req))return new Response(null,{status:403});const user=await session();if(user?.role!=='admin')return new Response(null,{status:403});try{const body=await req.json();const database=await db();const users=database.collection('users');
 if(body.action==='create'){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email)||typeof body.password!=='string'||body.password.length<10||!(/^[a-z0-9][a-z0-9-]{2,49}$/).test(body.slug)||['login','api','recuperar','admin'].includes(body.slug))throw Error('Revisa el correo, el slug (3–50 caracteres) y la contraseña (mínimo 10 caracteres).');await users.insertOne({email:body.email.toLowerCase(),password:await hash(body.password,12),slug:body.slug,role:'student',active:true,draft:{...emptyProfile,name:body.name||'',email:body.email},published:null,updatedAt:new Date()});}
 else if(body.action==='settings'){await database.collection('settings').updateOne({key:'general'},{$set:{institution:String(body.institution).slice(0,200),supportEmail:String(body.supportEmail).slice(0,200)}},{upsert:true});}
 else if(body.action==='backup'){return NextResponse.json({version:1,users:await users.find({role:'student'},{projection:{password:0}}).toArray(),settings:await database.collection('settings').findOne({key:'general'}),requests:await database.collection('recoveryRequests').find({resolved:false}).toArray()});}
 else if(body.action==='restore'){if(body.backup?.version!==1||!Array.isArray(body.backup.users)||body.backup.users.length>5000)throw Error('Copia no válida');for(const record of body.backup.users){if(!ObjectId.isValid(record._id))throw Error('Identificador no válido');await users.updateOne({_id:new ObjectId(record._id),role:'student'},{$set:{draft:profileSchema.parse(record.draft),published:record.published?profileSchema.parse(record.published):null,active:!!record.active,updatedAt:new Date()}});}if(body.backup.settings){const {institution,supportEmail}=body.backup.settings;await database.collection('settings').updateOne({key:'general'},{$set:{institution:String(institution||''),supportEmail:String(supportEmail||'')}},{upsert:true});}}
 else {if(!ObjectId.isValid(body.id))throw Error('Cuenta no válida');const filter={_id:new ObjectId(body.id),role:'student'};if(body.action==='toggle')await users.updateOne(filter,{$set:{active:!!body.active,updatedAt:new Date()}});else if(body.action==='delete')await users.deleteOne(filter);else if(body.action==='reset'){if(typeof body.password!=='string'||body.password.length<10)throw Error('Usa al menos 10 caracteres');await users.updateOne(filter,{$set:{password:await hash(body.password,12),sessionVersion:Date.now()}});await database.collection('recoveryRequests').updateOne({userId:new ObjectId(body.id)},{$set:{resolved:true}});}else throw Error('Acción no válida');}return NextResponse.json({ok:true});
 }catch(error){return NextResponse.json({error:(error as {code?:number}).code===11000?'El correo o el slug ya existe.':error instanceof Error?error.message:'No se pudo completar la acción'},{status:400});}}

